# USER CONTROLLER
### get all users
GET http://localhost:8090/api/v1/users

### get a user by id
GET http://localhost:8090/api/v1/users/1

### get all of a user's friendgroups
GET http://localhost:8090/api/v1/users/1/friendgroups

### get bulk users
GET http://localhost:8090/api/v1/users/bulk
Content-Type: application/json

{
  "ids": [1, 2, 3]
}

### create user
POST http://localhost:8090/api/v1/users
Content-Type: application/json

{
  "username": "Patrick",
  "profile_picture_source": "https://i.pinimg.com/736x/71/68/55/716855342150cda2755257f84c48028a.jpg",
  "email": "patrickstar@rockbottom.net"
}

### update user
PUT http://localhost:8090/api/v1/users/11
Content-Type: application/json

{
  "username": "Patrick Star"
}

### delete user
DELETE http://localhost:8090/api/v1/users/18

# ACTIVITY CONTROLLER
### get activities for single user
GET http://localhost:8090/api/v1/activities/22

### get all activities for friendgroup
GET http://localhost:8090/api/v1/activities/friendgroups/1

### get all activities for multiple friendgroups
GET http://localhost:8090/api/v1/activities/friendgroups?ids=1

### create activity
POST http://localhost:8090/api/v1/activities
Content-Type: application/json

{
  "activity_description": "Morning run",
  "activity_type": "running",
  "activity_date": "2023-10-01",
  "duration_m": 30,
  "thumbnail_src": "https://www.pngitem.com/pimgs/m/43-437426_running-man-free-pictures-man-running-png-transparent.png",
  "user_id": 3
}

### update activity
PUT http://localhost:8090/api/v1/activities/9
Content-Type: application/json

{
  "duration_m": 40
}

### delete activity
DELETE http://localhost:8090/api/v1/activities/8

# FRIENDGROUP CONTROLLER
### get friendgroup by id
GET http://localhost:8090/api/v1/friendgroups/1

### get all friendgroups for user
GET http://localhost:8090/api/v1/friendgroups/user/2

### remove user from friendgroup
DELETE http://localhost:8090/api/v1/friendgroups/1/user/2

### add user to friendgroup
POST http://localhost:8090/api/v1/friendgroups/1/user/2